package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import io.micrometer.core.instrument.Timer;
import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    @Autowired(required = false)
    private MetricsService metricsService;

    public List<UserResponse> getAllUsers() {
        beginDbOperation();
        try {
            return userRepository.findAll().stream()
                    .map(this::toResponse)
                    .toList();
        } finally {
            endDbOperation();
        }
    }

    public UserResponse getUserById(String id) throws EntityNotFoundException {
        Timer.Sample sample = startUserLookupTimer();
        beginDbOperation();
        try {
            UserEntity user = userRepository.findById(id)
                    .orElseThrow(() -> new EntityNotFoundException(id));
            return toResponse(user);
        } finally {
            endDbOperation();
            stopUserLookupTimer(sample);
        }
    }

    public UserEntity getUserEntityById(String id) throws EntityNotFoundException {
        return userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public UserResponse createUser(CreateUserRequest request) {
        beginDbOperation();
        try {
            if (userRepository.findByEmail(request.email()).isPresent()) {
                throw new IllegalArgumentException("Email already exists: " + request.email());
            }
            UserEntity user = new UserEntity(
                    null, // ID will be generated by the repository
                    request.name(),
                    request.email()
            );
            UserEntity saved = userRepository.save(user);
            recordUserCreated();
            return toResponse(saved);
        } catch (RuntimeException ex) {
            recordUserCreationFailed();
            throw ex;
        } finally {
            endDbOperation();
        }
    }

    public UserResponse changeName(String id, String newName) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        UserEntity updated = new UserEntity(existing.id(), newName, existing.email());
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public void deleteUser(String id) throws EntityNotFoundException {
        if (!userRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        userRepository.deleteById(id);
    }

    public UserResponse getUserByEmail(String email) throws EntityNotFoundException {
        Timer.Sample sample = startUserLookupTimer();
        beginDbOperation();
        try {
            UserEntity user = userRepository.findByEmail(email)
                    .orElseThrow(() -> new EntityNotFoundException(email));
            return toResponse(user);
        } finally {
            endDbOperation();
            stopUserLookupTimer(sample);
        }
    }

    public UserEntity getUserEntityByEmail(String email) throws EntityNotFoundException {
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException(email));
    }

    private UserResponse toResponse(UserEntity user) {
        return new UserResponse(
                user.id(),
                user.name(),
                user.email()
        );
    }

    private Timer.Sample startUserLookupTimer() {
        return metricsService == null ? null : metricsService.startUserLookupTimer();
    }

    private void stopUserLookupTimer(Timer.Sample sample) {
        if (metricsService != null && sample != null) {
            metricsService.stopUserLookupTimer(sample);
        }
    }

    private void recordUserCreated() {
        if (metricsService != null) {
            metricsService.recordUserCreated();
        }
    }

    private void recordUserCreationFailed() {
        if (metricsService != null) {
            metricsService.recordUserCreationFailed();
        }
    }

    private void beginDbOperation() {
        if (metricsService != null) {
            metricsService.beginDbOperation();
        }
    }

    private void endDbOperation() {
        if (metricsService != null) {
            metricsService.endDbOperation();
        }
    }
}
